# Generated by Django 6.0.2 on 2026-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user_id'),
        ('seller', '0004_user_alter_seller_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
