# Generated by Django 5.2.6 on 2026-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.FileField(default='images/customer_default.png', upload_to='images/'),
        ),
    ]
