# Generated by Django 6.0.2 on 2026-03-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_id_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
