# Generated by Django 6.0.2 on 2026-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
