# Generated by Django 6.0.2 on 2026-02-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user_id'),
        ('seller', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
