# Generated by Django 6.0.2 on 2026-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_user_alter_seller_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('pic', models.FileField(default='product_default.png', upload_to='media/images/')),
                ('description', models.TextField()),
                ('discount', models.IntegerField()),
                ('budge_text', models.CharField(max_length=20)),
                ('weight_unit', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
            ],
        ),
    ]
