# Generated by Django 6.0.2 on 2026-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(default='media/product_default.png', upload_to='media/images/'),
        ),
    ]
