# Generated by Django 6.0.2 on 2026-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_product_pic_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='images/product_default.png', upload_to='images/'),
        ),
    ]
