# Generated by Django 6.0.2 on 2026-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='media/product_default.png', upload_to='media/images/'),
        ),
    ]
