# Generated by Django 6.0.2 on 2026-03-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='seller_default.png', upload_to='images/'),
        ),
    ]
