# Generated by Django 6.0.2 on 2026-03-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_stock_name',
            new_name='seller_store_name',
        ),
    ]
