# Generated by Django 5.2.6 on 2026-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='images/seller_default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(default='images/product_default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
